version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmqCon

  mongo:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    container_name: mongoCon
    network_mode: host

  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysqlCon
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserDB
      MYSQL_USER: app_root
      MYSQL_PASSWORD: root

  zuul:
    image: zuul
    build: ZuulServer
    restart: always
    ports:
      - 9090:9090
    container_name: zuulgatewayCon
    depends_on:
      - eureka
    network_mode: host

  eureka:
    image: eureka
    build: EurekaServer
    restart: always
    ports:
      - 8761:8761
    container_name: eurekadiscoveryCon
    network_mode: host

  accountmanager:
    image: accountmanager
    build: accountmanager
    restart: always
    network_mode: host
    container_name: accountmanagerCon
    depends_on:
      - mysql
      - rabbitmq
      - eureka
    ports:
      - 8080:8080

  giphermanager:
    image: giphermanager
    build: giphermanager
    restart: always
    network_mode: host
    container_name: giphermanagerCon
    depends_on:
      - mongo
      - rabbitmq
      - eureka
    ports:
      - 8081:8081

  gipherrecommendations:
    image: gipherrecommendationsmanager
    build: gipherrecommendersystem
    restart: always
    network_mode: host
    container_name: gipherrecommendationsCon
    depends_on:
      - mongo
      - rabbitmq
      - eureka
    ports:
      - 8082:8082

  angular:
    image: frontend
    build: GipherUI
    network_mode: host
    container_name: front-end
    ports:
      - 4200:4200