spring:
  application:
    name: zuul-server

server:
  port: 9090


zuul:
  routes:
    accountmanager:
      url: http://localhost:8080
    giphermanager:
      url: http://localhost:8081
    gipherrecommendations:
      url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: routes, filters